#!/usr/bin/env python3
"""Regenerate _data/image_dims.yml: pixel dimensions for every image a post
references. _layouts/post.html stamps these onto <img> tags as width/height
attributes after markdownify, so the browser reserves each image's box before
the file arrives and image loads cause no layout shift.

Run after adding an image to a post: script/image-dims.py
A missing entry degrades gracefully — that image just gets no attributes.
"""
import glob, re, struct, subprocess, sys, os

os.chdir(os.path.join(os.path.dirname(__file__), '..'))

refs = set()
for p in glob.glob('_posts/*.md') + glob.glob('_posts/Drafts/*.md') + glob.glob('*.md'):
    s = open(p, encoding='utf-8').read()
    refs.update(re.findall(r'\]\(/?(assets/[^)\s]+)', s))
    refs.update(re.findall(r'src="/?(assets/[^"]+)', s))

EXT = ('.png', '.jpg', '.jpeg', '.gif', '.webp')
entries = []
skipped = 0
for path in sorted(refs):
    if not path.lower().endswith(EXT):
        continue
    if not os.path.isfile(path):
        print(f'  missing on disk, skipped: {path}', file=sys.stderr)
        skipped += 1
        continue
    out = subprocess.run(['sips', '-g', 'pixelWidth', '-g', 'pixelHeight', path],
                         capture_output=True, text=True)
    m = re.findall(r'pixel(?:Width|Height): (\d+)', out.stdout)
    if len(m) != 2:
        print(f'  sips failed, skipped: {path}', file=sys.stderr)
        skipped += 1
        continue
    entries.append((path, int(m[0]), int(m[1])))

with open('_data/image_dims.yml', 'w') as f:
    f.write('# Generated by script/image-dims.py — do not edit by hand.\n')
    f.write('# Read by _layouts/post.html to stamp width/height onto post images.\n')
    for path, w, h in entries:
        f.write(f'- path: "{path}"\n  w: {w}\n  h: {h}\n')

print(f'{len(entries)} images written, {skipped} skipped')
